# -*- coding: utf-8 -*-
"""project116.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sAUY-h3fw5PkMQauyw7CMcKQ3sORnCSS
"""

import csv
import pandas as pd
import plotly.express as px

df=pd.read_csv('project116.csv')

toefl_score=df['TOEFL Score'].tolist()
gre_score=df['GRE Score'].tolist()

fig=px.scatter(x=toefl_score,y=gre_score)
fig.show()

import csv
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

df=pd.read_csv('project116.csv')

toefl_score=df['TOEFL Score'].tolist()
gre_score=df['GRE Score'].tolist()
results=df['Chance of admit'].tolist()

colors=[]

for i in results:
  if i==1:
    colors.append('green')
  else:
    colors.append('red')

fig=go.Figure(data=go.Scatter(
    x=toefl_score,
    y=gre_score,
    mode='markers',
    marker=dict(color=colors)
))
fig.show()

import csv
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

df=pd.read_csv('project116.csv')

toefl_score=df['TOEFL Score'].tolist()
gre_score=df['GRE Score'].tolist()
results=df['Chance of admit'].tolist()


factors=df[['TOEFL Score','GRE Score']]
result=df['Chance of admit']

print(result)

from sklearn.model_selection import train_test_split

toefl_train,toefl_test,result_train,result_test=train_test_split(factors,result,test_size=0.25,random_state=0)
print(toefl_train)

from sklearn.linear_model import LogisticRegression

classifier=LogisticRegression(random_state=0)
classifier.fit(toefl_train,result_train)

result_pred=classifier.predict(toefl_test)

from sklearn.metrics import accuracy_score

print('accuracy:',accuracy_score(result_test,result_pred))

from sklearn.preprocessing import StandardScaler

sc_x=StandardScaler()
toefl_train=sc_x.fit_transform(toefl_train)

gre_score=int(input('Enter GRE Score'))
toefl_score=int(input('Enter TOEFL Score'))

user_test=sc_x.transform([[toefl_score,gre_score]])
user_pred=classifier.predict(user_test)

if user_pred[0]==1:
  print('May get admission')
else:
  print(' may not get admission')